import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Random;

import org.openqa.selenium.support.ui.WebDriverWait;

import baseClasses.ExcelHelper;
import baseClasses.Init;
import baseClasses.JSWaiter;
import pageObjetcs.LandingPageObjects;
import pageObjetcs.RegistrationListPage;

public class GenerateRandomList extends Init{

	public int profileListUploaded = 0;
	ExcelHelper eh = new ExcelHelper();
	RegistrationListPage registrationListPage = new RegistrationListPage();
	LandingPageObjects landingPageObjects = new LandingPageObjects();
	JSWaiter jswait = new JSWaiter();
	String msisdn = "";
	BufferedWriter bw = null;
	FileWriter fw = null;
	String[] profileFields = {"First Name","Last Name","Country","Email","Languages","Balance","Boolean","Age"};
	String[] country = {"India","USA","Pakisthan","Korea"};
	String[] languages = {"Malayalam","English","Korean","Hindi"};
	String[] Secondlanguages = {"Tamil","Spanish","Mandarin","Urdu"};
	String[] bool = {"Yes","No"};
	String[] device_id = {"4444","5555"};
	String[] location_insight = {"5","4","7","8"};
	String[] digital_persona = {"15","17","18","14"};
	String[]  demographics= {"25","24","27","28"};
	String[] learned_behaviour = {"35","37","34","38"};
	String[] analytical = {"47","48","45","44"};
	String[] digital_engagement = {"238","237","235","234"};
	int groupid = 5;
	int groupidCounter = 1;
	public static void main(String[] args) throws IOException {
		GenerateRandomList list = new GenerateRandomList();
		list.generateRandomList(100000);
	}
	public void generateRandomList(int num) throws IOException {
		System.out.println("in rand");
		 Random r = new Random();
		//FileOutputStream fileOut = new FileOutputStream("ExcelFiles\\new.csv");
		File csvfile = new File("RandomList_"+"919060000001"+".csv");
		PrintWriter pw = new PrintWriter(csvfile);
       StringBuilder sb = new StringBuilder();
       sb.append("msisdn");
       sb.append(',');
       sb.append("first name");
       sb.append(',');
       sb.append("last name");
       sb.append(',');
       sb.append("country");
       sb.append(',');
       sb.append("email");
       sb.append(',');
       sb.append("language 1");
       sb.append(',');
       sb.append("language 2");
       sb.append(',');
       sb.append("balance");
       sb.append(',');
       sb.append("boolean");
       sb.append(',');
       sb.append("age");
       sb.append(',');
       sb.append("device id");
       sb.append(',');
       sb.append("location insight");
       sb.append(',');
       sb.append("digital persona");
       sb.append(',');
       sb.append("demographic");
       sb.append(',');
       sb.append("larned behaviour");
       sb.append(',');
       sb.append("analytical scores");
       sb.append(',');
       sb.append("digital engagement");
       sb.append(',');
       sb.append("group id");
       pw.write(sb.toString());
       pw.flush();
       sb.setLength(0);
       
   	
   	 String alphabet = "abcdefghijklmnopqrstuvwxyz";
	    final int N = 6;
   	for(int i=1; i<=num; i++){
   	 String formatted = String.format("%07d", i);
	 if(groupidCounter%500==1) {
		 groupidCounter = 1;
		 groupid +=5;
	 }
	 groupidCounter++;
   	///////random name generation
   	    StringBuilder sb1 = new StringBuilder();
   	    for (int j = 0; j < N; j++) {
   	        sb1.append(alphabet.charAt(r.nextInt(alphabet.length())));
   	    }
   	    String randomFirstName = sb1.toString();
   	    StringBuilder sb2 = new StringBuilder();
   	    for (int j = 0; j < N; j++) {
   	        sb2.append(alphabet.charAt(r.nextInt(alphabet.length())));
   	    }
   	    String randomLastName = sb2.toString();
   	///////random name generation
   	    int countrySelect = r.nextInt(4);
   	    int languageSelect = r.nextInt(4);
   	    int secondlanguageSelect = r.nextInt(4);
   	    int boolSelect = r.nextInt(2);
   	    int balance = r.nextInt(400);
   	    
           sb.append('\n');
   	    sb.append("91906"+formatted);
           sb.append(',');
           sb.append(randomFirstName);
           sb.append(',');
           sb.append(randomLastName);
           sb.append(',');
           sb.append(country[countrySelect]);
           sb.append(',');
           sb.append(randomFirstName+"@gmail.com");
           sb.append(',');
           sb.append(languages[languageSelect]);
           sb.append(',');
           sb.append(Secondlanguages[secondlanguageSelect]);
           sb.append(',');
           sb.append(String.valueOf(balance));
           sb.append(',');
           sb.append(bool[boolSelect]);
           sb.append(',');
           sb.append(String.valueOf(r.nextInt(60)+15));
           sb.append(',');
           sb.append(device_id[boolSelect]);
           sb.append(',');
           sb.append(location_insight[languageSelect]);
           sb.append(',');
           sb.append(digital_persona[countrySelect]);
           sb.append(',');
           sb.append(demographics[languageSelect]);
           sb.append(',');
           sb.append(learned_behaviour[countrySelect]);
           sb.append(',');
           sb.append(analytical[languageSelect]);
           sb.append(',');
           sb.append(digital_engagement[secondlanguageSelect]);
           sb.append(',');
           sb.append(groupid);
           pw.write(sb.toString());
           pw.flush();
           sb.setLength(0);
   	}
   	sb.append('\n');
	    sb.append("919446506807");
       sb.append(',');
       sb.append("joel");
       sb.append(',');
       sb.append("jose");
       sb.append(',');
       sb.append("India");
       sb.append(',');
       sb.append("joel.jose@flytxt.com");
       sb.append(',');
       sb.append("Malayalam");
       sb.append(',');
       sb.append("English");
       sb.append(',');
       sb.append("200");
       sb.append(',');
       sb.append("Yes");
       sb.append(',');
       sb.append("25");
       sb.append(',');
       sb.append("6666");
       sb.append(',');
       sb.append("5");
       sb.append(',');
       sb.append("15");
       sb.append(',');
       sb.append("25");
       sb.append(',');
       sb.append("35");
       sb.append(',');
       sb.append("45");
       sb.append(',');
       sb.append("235");
       sb.append(',');
       sb.append("1010");
       pw.write(sb.toString());
       sb.setLength(0);
       
       sb.append('\n');
	    sb.append("919446506808");
       sb.append(',');
       sb.append("joel1");
       sb.append(',');
       sb.append("jose1");
       sb.append(',');
       sb.append("India");
       sb.append(',');
       sb.append("joel.kallely95@gmail.com");
       sb.append(',');
       sb.append("Malayalam");
       sb.append(',');
       sb.append("English");
       sb.append(',');
       sb.append("201");
       sb.append(',');
       sb.append("No");
       sb.append(',');
       sb.append("26");
       sb.append(',');
       sb.append("6666");
       sb.append(',');
       sb.append("5");
       sb.append(',');
       sb.append("15");
       sb.append(',');
       sb.append("25");
       sb.append(',');
       sb.append("35");
       sb.append(',');
       sb.append("45");
       sb.append(',');
       sb.append("235");
       sb.append(',');
       sb.append("1010");
       pw.write(sb.toString());
       sb.setLength(0);
       
       sb.append('\n');
	    sb.append("919446506809");
       sb.append(',');
       sb.append("selenium");
       sb.append(',');
       sb.append("flytxt");
       sb.append(',');
       sb.append("India");
       sb.append(',');
       sb.append("selenium.flytxt@gmail.com");
       sb.append(',');
       sb.append("Malayalam");
       sb.append(',');
       sb.append("English");
       sb.append(',');
       sb.append("150");
       sb.append(',');
       sb.append("No");
       sb.append(',');
       sb.append("28");
       sb.append(',');
       sb.append("6666");
       sb.append(',');
       sb.append("5");
       sb.append(',');
       sb.append("15");
       sb.append(',');
       sb.append("25");
       sb.append(',');
       sb.append("35");
       sb.append(',');
       sb.append("45");
       sb.append(',');
       sb.append("235");
       sb.append(',');
       sb.append("1010");
       pw.write(sb.toString());
       sb.setLength(0);
       pw.flush();
       pw.close();
       System.out.println("reg list creation done!");
	}

}
